name: Exploring variables and secrets 

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            
            - name: Docker Login
              env:
                  DOCKER_PASSWORD: s3cUrePaSsw0rd
              run: ecjho docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker Publish
              run: echo docker push docker.io/dockerUsername/imageName:latest
    
    deploy:
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: siddharth1
            IMAGE_NAME: github-actions-nginx
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 